services:
  db:
    container_name: auth-pet-store
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth
    ports:
      - 5445:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: